global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'bot'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8091']

  - job_name: 'scrapper'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']